const PrivacyPolicy = () => {
  return (
    <div>
      <div id="wrap">
        <div id="content">
          <section className="history-block padding-top-100 padding-bottom-100">
            <div className="container">
              <div className="row">
                <div className="col-xs-10 center-block">
                  <div className="vision-text">
                    <div className="col-lg-5">
                      <h2>Privacy Policy</h2>
                    </div>
                    <br />

                    <div className="col-lg-7">
                      <p>
                        Our Privacy Policy was last updated on March 2022. This
                        Privacy Policy describes Our policies and procedures on
                        the collection, use and disclosure of Your information
                        when You use the Service and tells You about Your
                        privacy rights and how the law protects You. We use Your
                        Personal data to provide and improve the Service. By
                        using the Service, You agree to the collection and use
                        of information in accordance with this Privacy Policy.
                        This Privacy Policy was generated by TermsFeed Privacy
                        Policy Generator.
                        <br />
                        <br />
                        <div className="title">Interpretation</div>
                        <br />
                        The words of which the initial letter is capitalized
                        have meanings defined under the following conditions.
                        The following definitions shall have the same meaning
                        regardless of whether they appear in singular or in
                        plural.
                        <br />
                        <br />
                        <div className="title">Definition</div>
                        <br />
                        For the purposes of this Privacy Policy:
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Account :</div>
                            means a unique account created for You to access our
                            Service or parts of our Service.
                          </li>
                          <br />

                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers' personal information and
                            determines the purposes and means of the processing
                            of Consumers' personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers' personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                        </ul>
                        For the purpose of the GDPR, the Company is the Data
                        Controller.
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Country :</div>
                            refers to Canada.
                          </li>
                          <br />

                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers' personal information and
                            determines the purposes and means of the processing
                            of Consumers' personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers' personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                        </ul>
                        <br />
                        <br />
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
