import Link from "next/link";

const PrivacyPolicy = () => {
  return (
    <div id="privacy-shipping">
      <div id="wrap">
        <div id="content">
          <section className="history-block padding-top-100 padding-bottom-100">
            <div className="container">
              <div className="row">
                <div className="col-xs-10 center-block">
                  <div className="vision-text">
                    <div className="col-lg-5">
                      <h2>Privacy Policy</h2>
                    </div>
                    <br />

                    <div className="col-lg-7">
                      <p>
                        Our Privacy Policy was last updated on March 2022. This
                        Privacy Policy describes Our policies and procedures on
                        the collection, use and disclosure of Your information
                        when You use the Service and tells You about Your
                        privacy rights and how the law protects You. We use Your
                        Personal data to provide and improve the Service. By
                        using the Service, You agree to the collection and use
                        of information in accordance with this Privacy Policy.
                        This Privacy Policy was generated by TermsFeed Privacy
                        Policy Generator.
                        <br />
                        <br />
                        <div className="title">Interpretation</div>
                        <br />
                        The words of which the initial letter is capitalized
                        have meanings defined under the following conditions.
                        The following definitions shall have the same meaning
                        regardless of whether they appear in singular or in
                        plural.
                        <br />
                        <br />
                        <div className="title">Definition</div>
                        <br />
                        For the purposes of this Privacy Policy:
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Account :</div>
                            means a unique account created for You to access our
                            Service or parts of our Service.
                          </li>
                          <br />

                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers&apos; personal information and
                            determines the purposes and means of the processing
                            of Consumers&apos; personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers&apos; personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                        </ul>
                        For the purpose of the GDPR, the Company is the Data
                        Controller.
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Country :</div>
                            refers to Canada.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Data Controller :</div>
                            for the purposes of the GDPR (General Data
                            Protection Regulation), refers to the Company as the
                            legal person which alone or jointly with others
                            determines the purposes and means of the processing
                            of Personal Data.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers&apos; personal information and
                            determines the purposes and means of the processing
                            of Consumers&apos; personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers&apos; personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Consumer :</div>
                            or the purpose of the CCPA (Canada Consumer Privacy
                            Act), means a natural person who is a Canada
                            resident. A resident, as defined in the law,
                            includes (1) every individual who is in the Canada
                            for other than a temporary or transitory purpose,
                            and (2) every individual who is domiciled in the
                            Canada who is outside the Canada for a temporary or
                            transitory purpose.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Cookies :</div>
                            are small files that are placed on Your computer,
                            mobile device or any other device by a website,
                            containing the details of Your browsing history on
                            that website among its many uses.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Device :</div> means any
                            device that can access the Service such as a
                            computer, a cell phone or a digital tablet.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Do Not Track (DNT) :</div> is
                            a concept that has been promoted by CA regulatory
                            authorities, in particular the Canada Federal Trade
                            Commission , for the Internet industry to develop
                            and implement a mechanism for allowing internet
                            users to control the tracking of their online
                            activities across websites.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Personal Data :</div> is any
                            information that relates to an identified or
                            identifiable individual. For the purposes of GDPR,
                            Personal Data means any information relating to You
                            such as a name, an identification number, location
                            data, online identifier or to one or more factors
                            specific to the physical, physiological, genetic,
                            mental, economic, cultural or social identity. For
                            the purposes of the CCPA, Personal Data means any
                            information that identifies, relates to, describes
                            or is capable of being associated with, or could
                            reasonably be linked, directly or indirectly, with
                            You.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Sale : </div> for the purpose
                            of the CCPA (Canada Consumer Privacy Act), means
                            selling, renting, releasing, disclosing,
                            disseminating, making available, transferring , or
                            otherwise communicating orally, in writing, or by
                            electronic or other means, a Consumers personal
                            information to another business or a third party for
                            monetary or other valuable consideration.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Service :</div> refers to the
                            Website.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Usage Data</div> refers to
                            data collected automatically, either generated by
                            the use of the Service or from the Service
                            infrastructure itself (for example, the duration of
                            a page visit).
                          </li>
                          <br />
                          <li>
                            <li>
                              <div className="bold">Service Provider</div> means
                              any natural or legal person who processes the data
                              on behalf of the Company. It refers to third
                              <br />
                              party companies or individuals employed by the
                              Company to facilitate the Service, to provide the
                              Service on behalf of the Company, to perform
                              services related to the Service or to assist the
                              Company in analyzing how the Service is used. For
                              the purpose of the GDPR, Service Providers are
                              considered Data Processors.
                            </li>
                            <br />
                            <div className="bold">Website</div> refers to
                            [WEBSITE NAME], accessible from [WEBSITE_URL]
                          </li>
                          <br />
                          <li>
                            <div className="bold">You</div> means the individual
                            accessing or using the Service, or the company, or
                            other legal entity on behalf of which such
                            individual is accessing or using the Service, as
                            applicable. Under GDPR (General Data Protection
                            Regulation), You can be referred to as the Data
                            Subject or as the User as you are the individual
                            using the Service.
                          </li>
                          <br />
                        </ul>
                        <ul className="column">
                          <div className="title">
                            Collecting and Using Your Personal Data
                          </div>
                          <div className="title">Types of Data Collected</div>
                          <div className="title">Personal Data</div>
                          <br />
                          <li>
                            <div className="bold">
                              To provide and maintain our Service :
                            </div>
                            including to monitor the usage of our Service.
                          </li>
                          <br />
                          <li>
                            <div className="bold">To manage Your Account :</div>
                            to manage Your registration as a user of the
                            Service. The Personal Data You provide can give You
                            access to different functionalities of the Service
                            that are available to You as a registered user.
                          </li>
                          <br />
                          <li>
                            <div className="bold">
                              For the performance of a contract:
                            </div>
                            the development, compliance and undertaking of the
                            purchase contract for the products, items or
                            services You have purchased or of any other contract
                            with Us through the Service.
                          </li>
                          <br />
                          <li>
                            <div className="bold">To contact You:</div> To
                            contact You by email, telephone calls, SMS, or other
                            equivalent forms of electronic communication, such
                            as a mobile application&apos;s push notifications
                            regarding updates or informative communications
                            related to the functionalities, products or
                            contracted services, including the security updates,
                            when necessary or reasonable for their
                            implementation.
                          </li>
                          <br />
                          <li>
                            <div className="bold">
                              To provide You with news :
                            </div>
                            special offers and general information about other
                            goods, services and events which we offer that are
                            similar to those that you have already purchased or
                            enquired about unless You have opted not to receive
                            such information.
                          </li>
                          <br />
                          <li>
                            <div className="bold">
                              To manage Your requests :
                            </div>
                            To attend and manage Your requests to Us.
                          </li>
                          <br />
                          <li>
                            <div className="bold">For business transfers :</div>
                            We may use Your information to evaluate or conduct a
                            merger, divestiture, restructuring, reorganization,
                            dissolution, or other sale or transfer of some or
                            all of Our assets, whether as a going concern or as
                            part of bankruptcy, liquidation, or similar
                            proceeding, in which Personal Data held by Us about
                            our Service users is among the assets transferred.
                          </li>
                          <br />
                          <li>
                            <div className="bold">For other purposes :</div> We
                            may use Your information for other purposes, such as
                            data analysis, identifying usage trends, determining
                            the effectiveness of our promotional campaigns and
                            to evaluate and improve our Service, products,
                            services, marketing and your experience.
                          </li>
                          <br />
                        </ul>
                        We may share Your personal information in the following
                        situations:
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">With Service Providers :</div>
                            We may share Your personal information with Service
                            Providers to monitor and analyze the use of our
                            Service, for payment processing, to contact You.
                          </li>
                          <br />
                          <li>
                            <div className="bold">For business transfers :</div>
                            We may share or transfer Your personal information
                            in connection with, or during negotiations of, any
                            merger, sale of Company assets, financing, or
                            acquisition of all or a portion of Our business to
                            another company.
                          </li>
                          <br />
                          <li>
                            <div className="bold">With Affiliates :</div> We may
                            share Your information with Our affiliates, in which
                            case we will require those affiliates to honor this
                            Privacy Policy. Affiliates include Our parent
                            company and any other subsidiaries, joint venture
                            partners or other companies that We control or that
                            are under common control with Us.
                          </li>
                          <br />
                          <li>
                            <div className="bold">With business partners :</div>
                            We may share Your information with Our business
                            partners to offer You certain products, services or
                            promotions.
                          </li>
                          <br />
                          <li>
                            <div className="bold">With other users :</div> when
                            You share personal information or otherwise interact
                            in the public areas with other users, such
                            information may be viewed by all users and may be
                            publicly distributed outside.
                          </li>
                          <br />
                          <li>
                            <div className="bold">With Your consent :</div> We
                            may disclose Your personal information for any other
                            purpose with Your consent.
                          </li>
                          <br />
                        </ul>
                        <br />
                        <div className="title">
                          Retention of Your Personal Data
                        </div>
                        <br />
                        The Company will retain Your Personal Data only for as
                        long as is necessary for the purposes set out in this
                        Privacy Policy. We will retain and use Your Personal
                        Data to the extent necessary to comply with our legal
                        obligations (for example, if we are required to retain
                        your data to comply with applicable laws), resolve
                        disputes, and enforce our legal agreements and policies.
                        <br />
                        <br />
                        The Company will also retain Usage Data for internal
                        analysis purposes. Usage Data is generally retained for
                        a shorter period of time, except when this data is used
                        to strengthen the security or to improve the
                        functionality of Our Service, or We are legally
                        obligated to retain this data for longer time periods.
                        <br />
                        <br />
                        <div className="title">
                          Transfer of Your Personal Data
                        </div>
                        <br />
                        Your information, including Personal Data, is processed
                        at the Company&apos;s operating offices and in any other
                        places where the parties involved in the processing are
                        located. It means that this information may be
                        transferred to — and maintained on — computers located
                        outside of Your state, province, country or other
                        governmental jurisdiction where the data protection laws
                        may differ than those from Your jurisdiction. Your
                        consent to this Privacy Policy followed by Your
                        submission of such information represents Your agreement
                        to that transfer.
                        <br />
                        <br />
                        The Company will take all steps reasonably necessary to
                        ensure that Your data is treated securely and in
                        accordance with this Privacy Policy and no transfer of
                        Your Personal Data will take place to an organization or
                        a country unless there are adequate controls in place
                        including the security of Your data and other personal
                        information.
                        <br />
                        <br />
                        <div className="title">
                          Disclosure of Your Personal Data
                        </div>
                        <br />
                        <div className="bold">Business Transactions :</div>
                        If the Company is involved in a merger, acquisition or
                        asset sale, Your Personal Data may be transferred. We
                        will provide notice before Your Personal Data is
                        transferred and becomes subject to a different Privacy
                        Policy.
                        <br />
                        <br />
                        <div className="bold">Law enforcement</div>
                        Under certain circumstances, the Company may be required
                        to disclose Your Personal Data if required to do so by
                        law or in response to valid requests by public
                        authorities (e.g. a court or a government agency).
                        <br />
                        <br />
                        <div className="bold">Other legal requirements</div>
                        The Company may disclose Your Personal Data in the good
                        faith belief that such action is necessary to:
                        <br />
                        <br />
                        <ul>
                          <li> - Comply with a legal obligation </li>
                          <li>
                            - Protect and defend the rights or property of the
                            Company
                          </li>
                          <li>
                            - Prevent or investigate possible wrongdoing in
                            connection with the Service
                          </li>
                          <li>
                            - Protect the personal safety of Users of the
                            Service or the public
                          </li>
                          <li> - Protect against legal liability </li>
                        </ul>
                        <br />
                        <div className="title">
                          Security of Your Personal Data
                        </div>
                        <br />
                        The security of Your Personal Data is important to Us,
                        but remember that no method of transmission over the
                        Internet, or method of electronic storage is 100%
                        secure. While We strive to use commercially acceptable
                        means to protect Your Personal Data, We cannot guarantee
                        its absolute security.
                        <br />
                        <br />
                        <div className="title">
                          Detailed Information on the Processing of Your
                          Personal Data
                        </div>
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Analytics</div>We may use
                            third-party Service providers to monitor and analyze
                            the use of our Service.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Email Marketing</div>
                            We may use Your Personal Data to contact You with
                            newsletters, marketing or promotional materials and
                            other information that may be of interest to You.
                            You may opt-out of receiving any, or all, of these
                            communications from Us by following the unsubscribe
                            link or instructions provided in any email We send
                            or by contacting Us.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Payments</div>
                            We may provide paid products and/or services within
                            the Service. In that case, we may use third-party
                            services for payment processing (e.g. payment
                            processors). We will not store or collect Your
                            payment card details. That information is provided
                            directly to Our third-party payment processors whose
                            use of Your personal information is governed by
                            their Privacy Policy. These payment processors
                            adhere to the standards set by PCI-DSS as managed by
                            the PCI Security Standards Council, which is a joint
                            effort of brands like Visa, Mastercard, American
                            Express and Discover. PCI-DSS requirements help
                            ensure the secure handling of payment information.
                          </li>
                          <br />
                          <li>
                            <div className="bold"></div>
                          </li>
                        </ul>
                        <div className="title">Modification</div>
                        <br />
                        This Privacy Policy may be amended from time to time in
                        order to maintain compliance with the law and to reflect
                        any changes to our data collection process. When we
                        amend this Privacy Policy we will update the &quot;Effective
                        Date&quot; at the top of this Privacy Policy. We recommend
                        that our users periodically review our Privacy Policy to
                        ensure that they are notified of any updates. If
                        necessary, we may notify users by email of changes to
                        this Privacy Policy.
                        <br />
                        <br />
                        <div className="title">Complaints</div>
                        <br />
                        If you have any concerns about how we handle your
                        personal data, please contact us using the contact
                        information <Link href="/contact">here</Link>.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
