const PrivacyPolicy = () => {
  return (
    <div>
      <div id="wrap">
        <div id="content">
          <section className="history-block padding-top-100 padding-bottom-100">
            <div className="container">
              <div className="row">
                <div className="col-xs-10 center-block">
                  <div className="vision-text">
                    <div className="col-lg-5">
                      <h2>Privacy Policy</h2>
                    </div>
                    <br />

                    <div className="col-lg-7">
                      <p>
                        Our Privacy Policy was last updated on March 2022. This
                        Privacy Policy describes Our policies and procedures on
                        the collection, use and disclosure of Your information
                        when You use the Service and tells You about Your
                        privacy rights and how the law protects You. We use Your
                        Personal data to provide and improve the Service. By
                        using the Service, You agree to the collection and use
                        of information in accordance with this Privacy Policy.
                        This Privacy Policy was generated by TermsFeed Privacy
                        Policy Generator.
                        <br />
                        <br />
                        <div className="title">Interpretation</div>
                        <br />
                        The words of which the initial letter is capitalized
                        have meanings defined under the following conditions.
                        The following definitions shall have the same meaning
                        regardless of whether they appear in singular or in
                        plural.
                        <br />
                        <br />
                        <div className="title">Definition</div>
                        <br />
                        For the purposes of this Privacy Policy:
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Account :</div>
                            means a unique account created for You to access our
                            Service or parts of our Service.
                          </li>
                          <br />

                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers' personal information and
                            determines the purposes and means of the processing
                            of Consumers' personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers' personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                        </ul>
                        For the purpose of the GDPR, the Company is the Data
                        Controller.
                        <br />
                        <br />
                        <ul className="column">
                          <li>
                            <div className="bold">Country :</div>
                            refers to Canada.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Data Controller :</div>
                            for the purposes of the GDPR (General Data
                            Protection Regulation), refers to the Company as the
                            legal person which alone or jointly with others
                            determines the purposes and means of the processing
                            of Personal Data.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Business :</div>
                            for the purpose of the CCPA (Canada Consumer Privacy
                            Act), refers to the Company as the legal entity that
                            collects Consumers' personal information and
                            determines the purposes and means of the processing
                            of Consumers' personal information, or on behalf of
                            which such information is collected and that alone,
                            or jointly with others, determines the purposes and
                            means of the processing of consumers' personal
                            information, that does business in the State of
                            Canada.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Consumer :</div>
                            or the purpose of the CCPA (Canada Consumer Privacy
                            Act), means a natural person who is a Canada
                            resident. A resident, as defined in the law,
                            includes (1) every individual who is in the USA for
                            other than a temporary or transitory purpose, and
                            (2) every individual who is domiciled in the USA who
                            is outside the USA for a temporary or transitory
                            purpose.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Cookies :</div>
                            are small files that are placed on Your computer,
                            mobile device or any other device by a website,
                            containing the details of Your browsing history on
                            that website among its many uses.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Device :</div> means any
                            device that can access the Service such as a
                            computer, a cell phone or a digital tablet.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Do Not Track (DNT) :</div> is
                            a concept that has been promoted by CA regulatory
                            authorities, in particular the Canada Federal Trade
                            Commission , for the Internet industry to develop
                            and implement a mechanism for allowing internet
                            users to control the tracking of their online
                            activities across websites.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Personal Data :</div> is any
                            information that relates to an identified or
                            identifiable individual. For the purposes of GDPR,
                            Personal Data means any information relating to You
                            such as a name, an identification number, location
                            data, online identifier or to one or more factors
                            specific to the physical, physiological, genetic,
                            mental, economic, cultural or social identity. For
                            the purposes of the CCPA, Personal Data means any
                            information that identifies, relates to, describes
                            or is capable of being associated with, or could
                            reasonably be linked, directly or indirectly, with
                            You.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Sale : </div> for the purpose
                            of the CCPA (Canada Consumer Privacy Act), means
                            selling, renting, releasing, disclosing,
                            disseminating, making available, transferring , or
                            otherwise communicating orally, in writing, or by
                            electronic or other means, a Consumers personal
                            information to another business or a third party for
                            monetary or other valuable consideration.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Service :</div> refers to the
                            Website.
                          </li>
                          <br />
                          <li>
                            <div className="bold">Usage Data</div> refers to
                            data collected automatically, either generated by
                            the use of the Service or from the Service
                            infrastructure itself (for example, the duration of
                            a page visit).
                          </li>
                          <br />
                          <li>
                            <li>
                              <div className="bold">Service Provider</div> means
                              any natural or legal person who processes the data
                              on behalf of the Company. It refers to third
                              <br />
                              party companies or individuals employed by the
                              Company to facilitate the Service, to provide the
                              Service on behalf of the Company, to perform
                              services related to the Service or to assist the
                              Company in analyzing how the Service is used. For
                              the purpose of the GDPR, Service Providers are
                              considered Data Processors.
                            </li>
                            <br />
                            <div className="bold">Website</div> refers to
                            [WEBSITE NAME], accessible from [WEBSITE_URL]
                          </li>
                          <br />
                          <li>
                            <div className="bold">You</div> means the individual
                            accessing or using the Service, or the company, or
                            other legal entity on behalf of which such
                            individual is accessing or using the Service, as
                            applicable. Under GDPR (General Data Protection
                            Regulation), You can be referred to as the Data
                            Subject or as the User as you are the individual
                            using the Service.
                          </li>
                          <br />
                        </ul>
                        <div className="title">
                          Collecting and Using Your Personal Data
                        </div>
                        <div className="title">Types of Data Collected</div>
                        <div className="title">Personal Data</div>
                        <br />
                        <li>
                          <div className="bold">
                            To provide and maintain our Service :
                          </div>
                          including to monitor the usage of our Service.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">
                            To manage Your Account :
                          </div>
                          to manage Your registration as a user of the Service.
                          The Personal Data You provide can give You access to
                          different functionalities of the Service that are
                          available to You as a registered user.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">
                            For the performance of a contract:
                          </div>
                          the development, compliance and undertaking of the
                          purchase contract for the products, items or services
                          You have purchased or of any other contract with Us
                          through the Service.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">To contact You:</div> To contact
                          You by email, telephone calls, SMS, or other
                          equivalent forms of electronic communication, such as
                          a mobile application's push notifications regarding
                          updates or informative communications related to the
                          functionalities, products or contracted services,
                          including the security updates, when necessary or
                          reasonable for their implementation.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">
                            To provide You with news :
                          </div>
                          special offers and general information about other
                          goods, services and events which we offer that are
                          similar to those that you have already purchased or
                          enquired about unless You have opted not to receive
                          such information.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">
                            To manage Your requests :
                          </div>
                          To attend and manage Your requests to Us.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">
                            For business transfers :
                          </div>
                          We may use Your information to evaluate or conduct a
                          merger, divestiture, restructuring, reorganization,
                          dissolution, or other sale or transfer of some or all
                          of Our assets, whether as a going concern or as part
                          of bankruptcy, liquidation, or similar proceeding, in
                          which Personal Data held by Us about our Service users
                          is among the assets transferred.
                        </li>
                        <br />
                        <li>
                          
                          <div className="bold">For other purposes :</div> We
                          may use Your information for other purposes, such as
                          data analysis, identifying usage trends, determining
                          the effectiveness of our promotional campaigns and to
                          evaluate and improve our Service, products, services,
                          marketing and your experience.
                        </li>
                        <br />
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
