import Head from "next/head";
import FeatureMessage from "../components/home/FeatureMessage";
import ProductCarousel from "../components/home/ProductCarousel";
import ProductList from "../components/home/ProductList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FeatureMessage
        title="New Arrivals"
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam"
      />
      <ProductList />

      <FeatureMessage
        title="Popular Products"
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam"
      />
      <ProductCarousel />
    </div>
  );
}
